gpio.mode(1, gpio.OUTPUT)
gpio.mode(2, gpio.OUTPUT)
gpio.mode(3, gpio.OUTPUT)
gpio.mode(4, gpio.OUTPUT)
gpio.mode(5, gpio.OUTPUT)
gpio.mode(6, gpio.OUTPUT)
gpio.mode(7, gpio.OUTPUT)

delayboot = 0

gpio.write(1, gpio.HIGH)
tmr.delay(delayboot)
gpio.write(1, gpio.LOW)
tmr.delay(delayboot)
gpio.write(2, gpio.HIGH)
tmr.delay(delayboot)
gpio.write(2, gpio.LOW)
tmr.delay(delayboot)
gpio.write(3, gpio.HIGH)
tmr.delay(delayboot)
gpio.write(3, gpio.LOW)
tmr.delay(delayboot)
gpio.write(4, gpio.HIGH)
tmr.delay(delayboot)
gpio.write(4, gpio.LOW)
tmr.delay(delayboot)
gpio.write(5, gpio.HIGH)
tmr.delay(delayboot)
gpio.write(5, gpio.LOW)
tmr.delay(delayboot)
gpio.write(6, gpio.HIGH)
tmr.delay(delayboot)
gpio.write(6, gpio.LOW)
tmr.delay(delayboot)
gpio.write(7, gpio.HIGH)
tmr.delay(delayboot)
gpio.write(7, gpio.LOW)

